name: Close Discussion on PR Merge

on:
  pull_request:
    types: [closed]  # Trigger only when the PR is closed

jobs:
  close-discussion:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is merged
      if: github.event.pull_request.merged == true
      run: |
        
        pr_body="${{ github.event.pull_request.body }}"
        discussion_id=$(echo "$pr_body" | grep -oP '#\d+' | sed 's/#//')
        pr_number="${{ github.event.pull_request.number }}"  # Get the PR number
        
            if [ -n "$discussion_id" ]; then
              echo "Discussion ID found: #$discussion_id"              
              token="${{ secrets.GITHUB_TOKEN }}"

              add_comment_query=$(echo "{\"query\": \"mutation { addDiscussionComment(input: {body: \\\"Merged with PR #$pr_number\\\", discussionId: \\\"$discussion_id\\\"}) { clientMutationId comment { id body } } }\"}")
      
              curl -X POST \
                -H "Authorization: Bearer $token" \
                -H "Content-Type: application/json" \
                -d "$add_comment_query" \
                "https://api.github.com/graphql"
      

              graphql_query=$(echo "{\"query\": \"mutation { updateDiscussion(input: {id: \\\"$discussion_id\\\", isAnswered: true}) { discussion { id title state } } }\"}")
              curl -X POST \
                -H "Authorization: Bearer $token" \
                -H "Content-Type: application/json" \
                -d "$graphql_query" \
                "https://api.github.com/graphql"
          
        else
          echo "No discussion ID found in the PR body."
        fi
