name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  
  schedule:
    - cron: '0 0 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/gh-runner-self:latest ./github/runner/docker

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/gh-runner-self:latest
