on:
  push:
    branches:
      - main
    paths:
      - 'json/**.json'
  workflow_dispatch: 

jobs:
  update-app-files:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Disable file mode changes detection
      - name: Disable file mode changes
        run: git config core.fileMode false

      # Step 3: Set up Git user for committing changes
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get changed files in PR
        id: changed-files
        run: | 
          CHANGED_FILES=$(gh pr diff --name-only ${{ github.event.pull_request.number }})  
          CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ' ')  
          echo "Changed files: $CHANGED_FILES"  
          echo "JSON_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Change JSON Date
        id: change-json-date
        run: |
          current_date=$(date +"%Y-%m-%d")

          for json_file in ${{ JSON_FILES }}; do
              current_json_date=$(jq -r '.date_created' "$json_file")

              if [[ "$current_json_date" != "$current_date" ]]; then
                echo "Updating $json_file with date $current_date"
                jq --arg date "$current_date" '.date_created = $date' "$json_file" > temp.json && mv temp.json "$json_file"
              else
                echo "Date in $json_file is already up to date."
              fi
            fi
          done


      # Step 6: Check if there are any changes
      - name: Check if there are any changes
        run: |
          echo "Checking for changes..."
          git add -A  # Untracked Dateien aufnehmen
          git status
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "changed=false" >> "$GITHUB_ENV"
          else
            echo "Changes detected:"
            git diff --stat --cached
            echo "changed=true" >> "$GITHUB_ENV"
          fi

      # Step 7: Commit and create PR if changes exist
      - name: Commit and create PR if changes exist
        if: env.changed == 'true'
        run: |
          git commit -m "Update .app files"
          git checkout -b pr-update-json-files
          git push origin pr-update-json-files --force
          gh pr create --title "[core] update .app files" \
                       --body "This PR is auto-generated by a GitHub Action to update the .app files." \
                       --head pr-update-json-files \
                       --base main \
                       --label "automated pr"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      
      - name: Approve pull request
        if: env.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --head "pr-update-json-files" --json number --jq '.[].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr review $PR_NUMBER --approve
          fi
          
      - name: Re-approve pull request after update
        if: env.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --head "pr-update-json-files" --json number --jq '.[].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr review $PR_NUMBER --approve
          fi

      # Step 8: Output success message when no changes
      - name: No changes detected
        if: env.changed == 'false'
        run: echo "No changes to commit. Workflow completed successfully."
