name: Update JSON Date

on:
  pull_request:
    paths:
      - 'ct/*.sh'
      - 'install/*-install.sh'
      - 'json/*.json'

jobs:
  update-json-date:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (for JSON manipulation)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Update JSON files
      run: |
        # Get the list of changed files in the pull request
        CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})

        # Iterate through changed files
        for FILE in $CHANGED_FILES; do
          # Check if the file matches the script patterns
          if [[ "$FILE" =~ ^ct/(.*)\.sh$ ]]; then
            NAME="${BASH_REMATCH[1]}"
          elif [[ "$FILE" =~ ^install/(.*)-install\.sh$ ]]; then
            NAME="${BASH_REMATCH[1]}"
          else
           if [[ "$FILE" =~ ^json/(.*)\.json$ ]]; then
            NAME="${BASH_REMATCH[1]}"
          else
            continue
          fi

          # Locate the corresponding JSON file
          JSON_FILE="json/${NAME}.json" # Adjust the path as necessary

          if [[ -f "$JSON_FILE" ]]; then
            echo "Updating date_created in $JSON_FILE"

            # Use jq to update the date_created field
            jq --arg date "$(date +%Y-%m-%d)" '.date_created = $date' "$JSON_FILE" > tmp.json && mv tmp.json "$JSON_FILE"
          else
            echo "JSON file $JSON_FILE not found"
          fi
        done


      - name: Push changes with API keys
        env:
          JSON_API_ID: ${{ secrets.JSON_API_ID }}
          JSON_API_KEY: ${{ secrets.JSON_API_KEY }}
        run: |
          git remote set-url origin https://$JSON_API_ID:$JSON_API_KEY@github.com/${{ github.repository }}.git
          git push
