name: Update JSON Date

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  update-json-date:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - run: |
        echo  "Fetch the base branch for comparison"
        BASE_BRANCH=${{ github.event.pull_request.base.ref }}
        HEAD_BRANCH=${{ github.event.pull_request.head.ref }}
        
        git fetch origin $BASE_BRANCH       
        
        CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH HEAD)
        
        echo "Changed files: $CHANGED_FILES"
       
        # Iterate through changed files
        for FILE in $CHANGED_FILES; do
          # Check if the file matches the script patterns
          if [[ "$FILE" =~ /(.*)\.sh ]]; then
            NAME="${BASH_REMATCH[1]}"
          elif [[ "$FILE" =~ /([^/]+)-[^/]+\.sh ]]; then
            NAME="${BASH_REMATCH[1]}"
          elif [[ "$FILE" =~ /(.*)\.json ]]; then
            NAME="${BASH_REMATCH[1]}"
          else
            echo "no Match on $FILE"
            continue
          fi
          
          # Locate the corresponding JSON file
          JSON_FILE="json/${NAME}.json" # Adjust the path as necessary

          if [[ -f "$JSON_FILE" ]]; then
            echo "Updating date_created in $JSON_FILE"

            # Use jq to update the date_created field
            jq --arg date "$(date +%Y-%m-%d)" '.date_created = $date' "$JSON_FILE" > tmp.json && mv tmp.json "$JSON_FILE"
          else
            echo "JSON file $JSON_FILE not found"
          fi
        done
             

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Date in $JSON_FILE"
        git push 

